name: beequest-borne

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERIAL_PORT=/dev/serial/by-id/usb-USBKey_Chip_USBKey_Module_202730041341-if00
    devices:
      - "/dev/serial/by-id/usb-USBKey_Chip_USBKey_Module_202730041341-if00:/dev/serial/by-id/usb-USBKey_Chip_USBKey_Module_202730041341-if00"
    restart: always
    networks:
      - beequest-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: always
    networks:
      - beequest-network

networks:
  beequest-network:
    driver: bridge